
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author msk
 */
public class NauczycielForm extends javax.swing.JFrame {
    protected ArrayList<String> listaPrzedmiotow = new ArrayList<String>();
    protected ArrayList<String> listaUczniow = new ArrayList<String>();
    protected ArrayList<String> listaKlas = new ArrayList<String>();
    private String Name;
    private String Surrname;
    private int id;
    private String username;
    private String password;
    
    /**
     * Creates new form NauczycielForm
     */
    public NauczycielForm(String Imie, String Nazwisko, String username) {
        this.Name = Imie;
        this.Surrname = Nazwisko;
        this.username = username;
        
        String data1 = "";
        String data2 = "";
        /*listaPrzedmiotow.add("Przyrka");
        listaPrzedmiotow.add("Gecia");
        listaUczniow.add("Jan Chujwalski");
        listaKlas.add("1A");*/
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");

             //conn = null;
            Connection conn = DriverManager.getConnection(DBConnector.url,DBConnector.username, DBConnector.password);
            
            String query = "SELECT idNau, Haslo from nauczyciel WHERE nazwaUz = ? AND imie = ? AND nazwisko = ? LIMIT 1";
            
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, this.username);
            preparedStmt.setString(2, this.Name);
            preparedStmt.setString(3, this.Surrname);
            ResultSet rs = preparedStmt.executeQuery();
            while (rs.next())
            {
                this.id = rs.getInt("idNau");
                this.password = rs.getString("Haslo");
            }
            
            String query2 = "SELECT DISTINCT k.Nazwaklasa, k.idklasa FROM nauczyciel n inner join przypisnau p on n.idNau=p.idNau inner join klasa k on k.idklasa=p.idklasa WHERE n.idNau=? ORDER BY k.idklasa";
            PreparedStatement preparedStmt2 = conn.prepareStatement(query2);
            preparedStmt2.setInt(1, this.id);
            ResultSet rs2 = preparedStmt2.executeQuery();
            while (rs2.next())
            {
                listaKlas.add(rs2.getString("k.Nazwaklasa"));
            }
            
            String query3 = "SELECT dataPocz, dataKon FROM datasem ORDER BY idSem DESC LIMIT 1";
            PreparedStatement preparedStmt3 = conn.prepareStatement(query3);
            ResultSet rs3 = preparedStmt3.executeQuery();
            while (rs3.next())
            {
                data1 = rs3.getString("datapocz");
                data2 = rs3.getString("dataKon");
            }

 
            conn.close();
          
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
            
        
        initComponents();
        for (int i = 0; i < listaKlas.size(); i++)
            {
                jNauczycielListaKlas.addItem(listaKlas.get(i));
            }
        jLabel1.setText("Panel nauczyciela: "+" "+this.Name+" "+this.Surrname);
        jLabel7.setText("Rok szkolny: "+" od "+data1+" do "+data2);

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDodajOcene = new javax.swing.JDialog();
        jDodajOcenePrzedmiotComboBox = new javax.swing.JComboBox();
        jWybierzUczniaComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jWybierzOceneComboBox = new javax.swing.JComboBox();
        jDodajOceneZatwierdzOceneButton = new javax.swing.JButton();
        jDodajOceneZakonczButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nazwaCw = new javax.swing.JTextField();
        jZmienHasloDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jEdytujHasloStare = new javax.swing.JPasswordField();
        jEdytujHasloNowe = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNauczycielWylogujButton = new javax.swing.JButton();
        jDodajOceneButton = new javax.swing.JButton();
        jNauczycielKlasyfikacjaButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jNauczycielListaKlas = new javax.swing.JComboBox();
        jNauczycielZmienHasloButton = new javax.swing.JButton();
        jEdytujOceny = new javax.swing.JButton();

        jDodajOcene.setTitle("Nauczyciel - dodaj ocenę");
        jDodajOcene.setMaximumSize(new java.awt.Dimension(419, 400));
        jDodajOcene.setMinimumSize(new java.awt.Dimension(419, 400));
        jDodajOcene.setPreferredSize(new java.awt.Dimension(419, 400));
        jDodajOcene.setResizable(false);

        jDodajOcenePrzedmiotComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        jDodajOcenePrzedmiotComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajOcenePrzedmiotComboBoxActionPerformed(evt);
            }
        });

        jWybierzUczniaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));

        jLabel2.setText("Wybierz Przedmiot: ");

        jLabel4.setText("Wybierz ucznia: ");

        jLabel5.setText("Wybierz ocenę: ");

        jWybierzOceneComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "2.5", "3", "3.5", "4", "4.5", "5"}));
        jWybierzOceneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWybierzOceneComboBoxActionPerformed(evt);
            }
        });

        jDodajOceneZatwierdzOceneButton.setText("Zatwierdź");
        jDodajOceneZatwierdzOceneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajOceneZatwierdzOceneButtonActionPerformed(evt);
            }
        });

        jDodajOceneZakonczButton.setText("Zakończ");
        jDodajOceneZakonczButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajOceneZakonczButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Nazwa ćwiczenia");

        javax.swing.GroupLayout jDodajOceneLayout = new javax.swing.GroupLayout(jDodajOcene.getContentPane());
        jDodajOcene.getContentPane().setLayout(jDodajOceneLayout);
        jDodajOceneLayout.setHorizontalGroup(
            jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDodajOceneLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDodajOceneLayout.createSequentialGroup()
                        .addComponent(jDodajOceneZatwierdzOceneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jDodajOceneZakonczButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDodajOceneLayout.createSequentialGroup()
                        .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDodajOcenePrzedmiotComboBox, 0, 200, Short.MAX_VALUE)
                            .addComponent(jWybierzUczniaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jWybierzOceneComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nazwaCw, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(20, 20, 20))
        );
        jDodajOceneLayout.setVerticalGroup(
            jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDodajOceneLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDodajOcenePrzedmiotComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWybierzUczniaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jWybierzOceneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nazwaCw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDodajOceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDodajOceneZatwierdzOceneButton)
                    .addComponent(jDodajOceneZakonczButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jZmienHasloDialog.setTitle("Nauczyciel - zmiana hasła");
        jZmienHasloDialog.setResizable(false);

        jLabel8.setText("Podaj stare hasło:");

        jLabel9.setText("Podaj nowe hasło:");

        jButton4.setText("Zatwierdź");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Anuluj");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jZmienHasloDialogLayout = new javax.swing.GroupLayout(jZmienHasloDialog.getContentPane());
        jZmienHasloDialog.getContentPane().setLayout(jZmienHasloDialogLayout);
        jZmienHasloDialogLayout.setHorizontalGroup(
            jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jZmienHasloDialogLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEdytujHasloStare, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jEdytujHasloNowe)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jZmienHasloDialogLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jZmienHasloDialogLayout.setVerticalGroup(
            jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jZmienHasloDialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jEdytujHasloStare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jEdytujHasloNowe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jZmienHasloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel nauczyciela");

        jLabel1.setText("Panel nauczyciela: ");

        jNauczycielWylogujButton.setText("Wyloguj się");
        jNauczycielWylogujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNauczycielWylogujButtonActionPerformed(evt);
            }
        });

        jDodajOceneButton.setText("Dodaj ocenę");
        jDodajOceneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajOceneButtonActionPerformed(evt);
            }
        });

        jNauczycielKlasyfikacjaButton.setText("Przejdź do klasyfikacji");
        jNauczycielKlasyfikacjaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNauczycielKlasyfikacjaButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Lista klas:");

        jLabel7.setText("Rok szkolny: ");

        jNauczycielListaKlas.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        jNauczycielListaKlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNauczycielListaKlasActionPerformed(evt);
            }
        });

        jNauczycielZmienHasloButton.setText("Zmień hasło");
        jNauczycielZmienHasloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNauczycielZmienHasloButtonActionPerformed(evt);
            }
        });

        jEdytujOceny.setText("Edytuj Oceny");
        jEdytujOceny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdytujOcenyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNauczycielKlasyfikacjaButton)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNauczycielZmienHasloButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNauczycielWylogujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDodajOceneButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jNauczycielListaKlas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jEdytujOceny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jNauczycielListaKlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDodajOceneButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEdytujOceny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jNauczycielZmienHasloButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNauczycielWylogujButton)
                    .addComponent(jNauczycielKlasyfikacjaButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jDodajOceneZakonczButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajOceneZakonczButtonActionPerformed
        jDodajOcene.dispose();
    }//GEN-LAST:event_jDodajOceneZakonczButtonActionPerformed

    private void jDodajOceneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajOceneButtonActionPerformed
        
        if (jNauczycielListaKlas.getItemCount()<1)
        {
            JOptionPane.showMessageDialog(null, "Nie można dodać pustej klasie oceny...");
        }
        else
        {
            try{
          ///////////////////////////////////////MOJE DO DIALOGA
           Class.forName("com.mysql.jdbc.Driver");

             //conn = null;
            Connection conn = DriverManager.getConnection(DBConnector.url,DBConnector.username, DBConnector.password);
            ResultSet rs3=null;            
            String query3 = "SELECT p.nazwaPrz FROM przypisnau pn "
                    + "JOIN nauczyciel n ON pn.idNau=n.idNau "
                    + "JOIN przedmiot p ON pn.idPrzed=p.idPrzed "
                    + "JOIN klasa k ON pn.idklasa=k.idklasa "
                    + "WHERE n.nazwaUz=? AND nazwaklasa=?";
            
            PreparedStatement preparedStmt3 = conn.prepareStatement(query3);
            preparedStmt3.setString(1, username);
            preparedStmt3.setString(2, (String)jNauczycielListaKlas.getSelectedItem());
            rs3 = preparedStmt3.executeQuery();
            
            //while (rs3.next())
            //    jDodajOcenePrzedmiotComboBox.addItem("");
            jDodajOcenePrzedmiotComboBox.removeAllItems();
            while (rs3.next())
                jDodajOcenePrzedmiotComboBox.addItem(rs3.getString("p.nazwaPrz"));
          ///////////////////////////////////////MOJE DO DIALOGA END
            conn.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
       /* for (int i = 0; i < listaPrzedmiotow.size(); i++)
        {
            jDodajOcenePrzedmiotComboBox.addItem(listaPrzedmiotow.get(i));
        }*/
        
//        for (int i = 0; i < listaKlas.size(); i++)
//        {
//            jWybierzKlaseComboBox.addItem(listaKlas.get(i));
//        }
        
//        for (int i = 0; i < listaUczniow.size(); i++)
//        {
//            jWybierzUczniaComboBox.addItem(listaUczniow.get(i));
//        }
        
        
        
                try{
          ///////////////////////////////////////MOJE DO DIALOGA kolejne
           Class.forName("com.mysql.jdbc.Driver");

             //conn = null;
            Connection conn = DriverManager.getConnection(DBConnector.url,DBConnector.username, DBConnector.password);
            ResultSet rs3=null;            
            String query3 = "SELECT DISTINCT u.nazwaUz, u.imie, u.nazwisko FROM uczen u "
                    + "JOIN tabelaczucznklasa t ON t.idUcz=u.idUcz "
                    + "JOIN klasa k ON k.idKlasa=t.idKlasa "
                    + "JOIN przypisnau pr ON pr.idKlasa=t.idKlasa WHERE pr.idNau=? AND k.nazwaKlasa=?";
            
            PreparedStatement preparedStmt3 = conn.prepareStatement(query3);
            preparedStmt3.setInt(1, id);
            
            
            preparedStmt3.setString(2, (String)jNauczycielListaKlas.getSelectedItem());
            rs3 = preparedStmt3.executeQuery();

            jWybierzUczniaComboBox.removeAllItems();
            while (rs3.next())
                jWybierzUczniaComboBox.addItem(rs3.getString("u.imie")+" "+rs3.getString("u.nazwisko")+" "+rs3.getString("u.nazwaUz"));
          ///////////////////////////////////////MOJE DO DIALOGA END
            conn.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        if (jWybierzUczniaComboBox.getItemCount()<1)
        {
            jDodajOceneZatwierdzOceneButton.setEnabled(false);
        }
        
        jDodajOcene.pack();
        jDodajOcene.setLocationRelativeTo(null);
        jDodajOcene.setVisible(true);
        }
                
    }//GEN-LAST:event_jDodajOceneButtonActionPerformed

    private void jNauczycielZmienHasloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNauczycielZmienHasloButtonActionPerformed
        jZmienHasloDialog.pack();
        jZmienHasloDialog.setLocationRelativeTo(null);
        jZmienHasloDialog.setVisible(true);
    }//GEN-LAST:event_jNauczycielZmienHasloButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jEdytujHasloStare.getText().equals(this.password) && jEdytujHasloNowe.getText().length() >= 6)
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");

                Connection conn = DriverManager.getConnection(DBConnector.url,DBConnector.username, DBConnector.password);
                
                String query = "UPDATE nauczyciel SET Haslo=? WHERE idNau = ? AND Imie=? AND Nazwisko=? AND nazwaUz=?";
                
                PreparedStatement preparedStmt = conn.prepareStatement(query);

                preparedStmt.setString(1, jEdytujHasloNowe.getText());
                preparedStmt.setInt(2, this.id);
                preparedStmt.setString(3, this.Name);
                preparedStmt.setString(4, this.Surrname);
                preparedStmt.setString(5, this.username);
                preparedStmt.executeUpdate();
                conn.close();


                jEdytujHasloStare.setText("");
                jEdytujHasloNowe.setText("");
                jZmienHasloDialog.setVisible(false); 
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
        }
        else
            JOptionPane.showMessageDialog(null, "Podane stare hasło jest nieprawidłowe lub nowe hasło nie zawiera więcej niż 6 znaków");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jEdytujHasloStare.setText("");
        jEdytujHasloNowe.setText("");
        
        jZmienHasloDialog.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jNauczycielWylogujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNauczycielWylogujButtonActionPerformed
        this.Name = "";
        this.Surrname = "";
        this.id = 0;
        this.username = "";
        this.password = "";
        
        login l = new login();
        l.pack();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jNauczycielWylogujButtonActionPerformed

    private void jDodajOceneZatwierdzOceneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajOceneZatwierdzOceneButtonActionPerformed
        // TODO add your handling code here:
        
        /////////dodawanie
        try
        {
            String query;
            Calendar cal = Calendar.getInstance();
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            String formatted = format1.format(cal.getTime());

            float val = Float.parseFloat((String)jWybierzOceneComboBox.getSelectedItem());
            String zaznaczone = (String)jWybierzUczniaComboBox.getSelectedItem();
            String[] Splited;
            Splited = zaznaczone.split(" ");
            query ="INSERT INTO ocena values (null, " +
                "?, " + //wartosc
                "?,"  + //nazwa
                "( SELECT idUcz FROM uczen WHERE nazwaUz=? LIMIT 1)," +
                "( SELECT idNau FROM nauczyciel WHERE nazwaUz=? LIMIT 1)," +
                "( SELECT idPrzed FROM przedmiot WHERE nazwaPrz=? LIMIT 1)," +
                "?," + //data
                //"( SELECT idSem FROM datasem WHERE dataPocz=? LIMIT 1))";
                "(  SELECT idSem FROM datasem ORDER BY idSem DESC LIMIT 1))";

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = null;
            conn = DriverManager.getConnection(DBConnector.url,DBConnector.username, DBConnector.password);
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setInt(1, (int)(10*val));
            preparedStmt.setString(2, nazwaCw.getText());
            preparedStmt.setString(3, Splited[2]);
            preparedStmt.setString(4, username);
            preparedStmt.setString(5, (String)jDodajOcenePrzedmiotComboBox.getSelectedItem());
            preparedStmt.setString(6, formatted);
            //preparedStmt.setString(7, "2019-02-14");


            preparedStmt.execute();

            conn.close();
            preparedStmt.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_jDodajOceneZatwierdzOceneButtonActionPerformed

    private void jWybierzOceneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWybierzOceneComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWybierzOceneComboBoxActionPerformed

    private void jNauczycielListaKlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNauczycielListaKlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNauczycielListaKlasActionPerformed

    private void jDodajOcenePrzedmiotComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajOcenePrzedmiotComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDodajOcenePrzedmiotComboBoxActionPerformed

    private void jNauczycielKlasyfikacjaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNauczycielKlasyfikacjaButtonActionPerformed
        try
        {
            NauczycielZakForm zakForm = new NauczycielZakForm(this.username, (String)jNauczycielListaKlas.getSelectedItem());
            zakForm.setVisible(true);
        }
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_jNauczycielKlasyfikacjaButtonActionPerformed

    private void jEdytujOcenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdytujOcenyActionPerformed
        try
        {
            NauczycielOcenyFrame nauOcFrame = new NauczycielOcenyFrame(this.username);
            nauOcFrame.setVisible(true);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jEdytujOcenyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NauczycielForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NauczycielForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NauczycielForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NauczycielForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NauczycielForm("","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDodajOcene;
    private javax.swing.JButton jDodajOceneButton;
    private javax.swing.JComboBox jDodajOcenePrzedmiotComboBox;
    private javax.swing.JButton jDodajOceneZakonczButton;
    private javax.swing.JButton jDodajOceneZatwierdzOceneButton;
    private javax.swing.JPasswordField jEdytujHasloNowe;
    private javax.swing.JPasswordField jEdytujHasloStare;
    private javax.swing.JButton jEdytujOceny;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jNauczycielKlasyfikacjaButton;
    private javax.swing.JComboBox jNauczycielListaKlas;
    private javax.swing.JButton jNauczycielWylogujButton;
    private javax.swing.JButton jNauczycielZmienHasloButton;
    private javax.swing.JComboBox jWybierzOceneComboBox;
    private javax.swing.JComboBox jWybierzUczniaComboBox;
    private javax.swing.JDialog jZmienHasloDialog;
    private javax.swing.JTextField nazwaCw;
    // End of variables declaration//GEN-END:variables
}
