
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin2
 */
public class NauczycielZakForm extends javax.swing.JFrame {

    private String nazwaKlasy;
    private String nazwaPrzedmiotu;
    /**
     * Creates new form NauczycielZakFrom
     */
    public NauczycielZakForm(String login, String NazwaKlasy) throws SQLException, ClassNotFoundException {
        ArrayList<String> listaPrzedmiotow = new ArrayList<String>();
        this.user=login;
        tm = new tModelNauZak();
        tm.readTables(login, NazwaKlasy, "","");
        this.nazwaKlasy = NazwaKlasy;
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");

             //conn = null;
            Connection conn = DriverManager.getConnection(DBConnector.url,DBConnector.username, DBConnector.password);
            String query3 = "SELECT p.nazwaPrz FROM przypisnau pn "
                    + "JOIN nauczyciel n ON pn.idNau=n.idNau "
                    + "JOIN przedmiot p ON pn.idPrzed=p.idPrzed "
                    + "JOIN klasa k ON pn.idklasa=k.idklasa "
                    + "WHERE n.nazwaUz=? AND nazwaklasa=?";
            
            PreparedStatement preparedStmt3 = conn.prepareStatement(query3);
            preparedStmt3.setString(1, login);
            preparedStmt3.setString(2, NazwaKlasy);
            ResultSet rs3 = preparedStmt3.executeQuery();
            
            while (rs3.next())
                listaPrzedmiotow.add(rs3.getString("p.nazwaPrz"));
            conn.close();
            rs3.close();
            for (int i = 0; i < listaPrzedmiotow.size(); i++)
                jWybierzPrzemdiotComboBox.addItem(listaPrzedmiotow.get(i));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(400);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jWybierzPrzemdiotComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jWybierzPrzedmiotButtonZatwierdz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nauczyciel - Panel klasyfikacji");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(tm);
        jScrollPane1.setViewportView(jTable1);

        jWybierzPrzemdiotComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel1.setText("Wybierz przedmiot");

        jWybierzPrzedmiotButtonZatwierdz.setText("Zatwierdź");
        jWybierzPrzedmiotButtonZatwierdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWybierzPrzedmiotButtonZatwierdzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jWybierzPrzemdiotComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jWybierzPrzedmiotButtonZatwierdz, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWybierzPrzemdiotComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jWybierzPrzedmiotButtonZatwierdz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDefaultCloseOperation(NauczycielZakForm.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jWybierzPrzedmiotButtonZatwierdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWybierzPrzedmiotButtonZatwierdzActionPerformed
        try {
            this.nazwaPrzedmiotu = (String)jWybierzPrzemdiotComboBox.getSelectedItem();
            tm.readTables(this.user, this.nazwaKlasy, "",this.nazwaPrzedmiotu);
            tm.fireTableDataChanged();
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jWybierzPrzedmiotButtonZatwierdzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NauczycielZakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NauczycielZakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NauczycielZakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NauczycielZakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NauczycielZakForm("","").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NauczycielZakForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NauczycielZakForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jWybierzPrzedmiotButtonZatwierdz;
    private javax.swing.JComboBox<String> jWybierzPrzemdiotComboBox;
    // End of variables declaration//GEN-END:variables


tModelNauZak tm;

String user;

}
